version: '3.9'
services:
  app:
    build: .
    ports:
      - "4628:4628"
    volumes:
      - .:/usr/src/app
      - grepbible-data:/root/.local/share/grepbible
    environment:
      - NODE_ENV=production
      - PORT=4628

volumes:
  grepbible-data:
