# Dockerfile.prod
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install PM2 globally for production process management
RUN npm install -g pm2

# Replace the CMD with a production-specific command
CMD ["pm2-runtime", "start", "server.js"]
