const BOOK2CHAPTERS = {
    '1 Chronicles': 29,
    '1 Corinthians': 16,
    '1 John': 5,
    '1 Kings': 22,
    '1 Peter': 5,
    '1 Samuel': 31,
    '1 Thessalonians': 5,
    '1 Timothy': 6,
    '2 Chronicles': 36,
    '2 Corinthians': 13,
    '2 John': 1,
    '2 Kings': 25,
    '2 Peter': 3,
    '2 Samuel': 24,
    '2 Thessalonians': 3,
    '2 Timothy': 4,
    '3 John': 1,
    'Acts': 28,
    'Amos': 9,
    'Colossians': 4,
    'Daniel': 12,
    'Deuteronomy': 34,
    'Ecclesiastes': 12,
    'Ephesians': 6,
    'Esther': 10,
    'Exodus': 40,
    'Ezekiel': 48,
    'Ezra': 10,
    'Galatians': 6,
    'Genesis': 50,
    'Habakkuk': 3,
    'Haggai': 2,
    'Hebrews': 13,
    'Hosea': 14,
    'Isaiah': 66,
    'James': 5,
    'Jeremiah': 52,
    'Job': 42,
    'Joel': 3,
    'John': 21,
    'Jonah': 4,
    'Joshua': 24,
    'Jude': 1,
    'Judges': 21,
    'Lamentations': 5,
    'Leviticus': 27,
    'Luke': 24,
    'Malachi': 4,
    'Mark': 16,
    'Matthew': 28,
    'Micah': 7,
    'Nahum': 3,
    'Nehemiah': 13,
    'Numbers': 36,
    'Obadiah': 1,
    'Philemon': 1,
    'Philippians': 4,
    'Proverbs': 31,
    'Psalms': 150,
    'Revelation': 22,
    'Romans': 16,
    'Ruth': 4,
    'Song of Solomon': 8,
    'Titus': 3,
    'Zechariah': 14,
    'Zephaniah': 3
};

module.exports = BOOK2CHAPTERS;
